### ISSUE TITLE
multiprocessing (fork issue)

### ISSUE THREAD

**Issue by delamarifer** [lcswillems/torch-ac#7]
Hi, I'm getting the same error as in this post: https://www.gitmemory.com/issue/lcswillems/rl-starter-files/48/721146262 

I tried adding the `if __name__ == '__main__':` line but it did not work.

**Comment by lcswillems** [comment]
Hi @delamarifer,

When I try to reproduce the error described in the Gitmemory, it works for me. I close this issue as I can't reproduce it. Don't hesitate to add more details on how to reproduce it (commands to execute) and I will reopen the issue.
